In [33]:
import pandas as pd
factor = pd.read_csv('C:\\Users\\86151\\data_for_reits\\factor_corr_analysis_data.csv',index_col=[0])

In [34]:
factor

,time,000832.CSI_close,000833.CSI_close,000845.CSI_close,000923.CSI_close,000012.SH_close,000101.SH_close,N11077.CSI_close,000013.CSI_close,950229.SH_close,...,180401.SZ_pvol_corr_prev,180401.SZ_large_trans_ret_prev,180501.SZ_rskew_prev,180501.SZ_reverse_prev,180501.SZ_pvol_corr_prev,180501.SZ_large_trans_ret_prev,180801.SZ_rskew_prev,180801.SZ_reverse_prev,180801.SZ_pvol_corr_prev,180801.SZ_large_trans_ret_prev
0,2021-06-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-06-22,377.5462,224.6660,201.4862,216.4346,186.7326,213.6703,152.7957,254.7212,173.580,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-06-23,380.0212,224.7666,201.4743,216.4849,186.7846,213.6951,152.8084,254.7733,173.679,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-06-24,381.5850,224.7854,201.5405,216.5182,186.8076,213.7187,152.8212,254.8166,173.799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-06-25,382.2409,224.7828,201.5974,216.5524,186.8187,213.7463,152.8324,254.8542,173.870,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,2023-07-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.100318,-0.002747,0.115370,0.00351,0.049327,0.007056,-0.126140,0.004311,-0.041633,0.002665
503,2023-07-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.138648,0.007005,-0.113213,0.00507,0.162851,0.017360,0.236464,0.013741,0.194403,0.007440
504,2023-07-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,2023-07-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,2023-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## VIF Analysis

In [35]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import warnings
warnings.filterwarnings('ignore')

In [36]:
import numpy as np

In [40]:
factor = factor.iloc[:,1:].fillna(factor.mean())

In [42]:
def calculate_vif(df):
    vif = pd.DataFrame()
    vif['index'] = df.columns
    vif['VIF'] = [variance_inflation_factor(df.values,i) for i in range(df.shape[1])]
    return vif

# 使用一个while循环逐步剔除变量

## 先计算每个变量的vif值，再重复计算
vif = calculate_vif(factor)
while (vif['VIF'] > 10).any():
    remove = vif.sort_values(by='VIF',ascending=False)['index'][:1].values[0]
    factor.drop(remove,axis=1,inplace=True)
    vif = calculate_vif(factor)

vif

                              index       VIF
0             950219CNY01.CSI_close  7.684952
1                               gdp  4.195961
2                            shibor  3.874938
3                    000832.CSI_amt  3.149222
4                    000833.CSI_amt  2.930520
..                              ...       ...
161  180501.SZ_large_trans_ret_prev  7.223961
162            180801.SZ_rskew_prev  2.589787
163          180801.SZ_reverse_prev  3.580680
164        180801.SZ_pvol_corr_prev  2.067710
165  180801.SZ_large_trans_ret_prev  3.855433

[166 rows x 2 columns]

In [64]:
vif_transform = vif.dropna(subset=['VIF']).sort_values(by='VIF',ascending=False,ignore_index=True)

In [65]:
vif_transform.to_csv('D:\\REITS研究数据\\VIF_subset.csv')